name = "gpsd_json"
version = "1.0.0"
licences = ["Apache-2.0"]
description = "Types and functions for working with GPSD's JSON API"
repository = { type = "github", user = "lpil", repo = "gpsd-json" }
links = [
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
  { title = "GPSD", href = "https://gpsd.io/index.html" },
  { title = "GPSD JSON", href = "https://gpsd.io/gpsd_json.html" },
]

target="javascript"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
decode = ">= 0.2.0 and < 1.0.0"
gleam_json = ">= 1.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
